server {
    listen 8085;
    server_name inherit.local;
    root ./www; # Raiz padrão do servidor (fallback)

    location / {
        index index.html;
    }

    location /docs/ {
        root ./www/documentation; # Raiz específica sobrescrita
    }

    location /images/ {
        # Nenhuma diretiva root declarada aqui -> Deve herdar o root do server pai!
    }
}
