server {
    listen 8082;
    server_name location-root.local;
    root ./www; # Raiz padrão do servidor

    location /images/ {
        root ./www/assets; # Raiz específica para essa location
    }
}