
server {
    listen 8088;
    server_name portfolio.com;
    root www/portfolio;

    location / {
        limit_except GET HEAD;
        autoindex off;
    }
}

server {
    listen 8088;
    server_name site-da-escola.com;
    root www/escola;

    location / {
        limit_except GET HEAD POST;
        autoindex on;
    }
}
