
server {
    listen 8088;
    server_name portfolio.com;
    root www/portfolio;

    location / {
        limit_except GET;
        autoindex off;
    }
}

server {
    listen 8088;
    server_name site-da-escola.com;
    root www/escola;

    location / {
        limit_except GET POST;
        autoindex on;
    }
}

#[Block] server (args: )
#  |-- [Directive] listen (args: 8088)
#  |-- [Directive] server_name (args: meu-portfolio.com)
#  |-- [Directive] root (args: /home/jucoelho/Juju_Cadete/Webserv/42-web-server/www/portfolio)
#  |
#  |-- [Block] location (args: /)
#        |-- [Directive] allowed_methods (args: GET)
#        |-- [Directive] autoindex (args: off)

#[Block] server (args: )
#  |-- [Directive] listen (args: 8088)
#  |-- [Directive] server_name (args: site-da-escola.com)
#  |-- [Directive] root (args: /home/jucoelho/Juju_Cadete/Webserv/42-web-server/www/escola)
#  |
#  |-- [Block] location (args: /)
#        |-- [Directive] allowed_methods (args: GET, POST)
#        |-- [Directive] autoindex (args: on)
