server {
    listen 8088;

    server_name localhost;

    root ./www;
    index index.html;

    location / {
        root ./www;
        index index.html;
    }

    location /old {
        return 301 /new;
    }

    location /new {
        root ./www;
        index index.html;
    }
}