server {
    listen 127.0.0.1:8081; # Coloquei 8080 porque o tester por padrão bate nessa porta
    server_name localhost;
    client_max_body_size 200M;

    location / {
        root eval_tests/YoupiBanane;
        index youpi.bad_extension;
        limit_except GET; # CORREÇÃO: O tester exige apenas GET na raiz
        autoindex off;
        cgi_pass .bla eval_tests/cgi_tester;
    }

    location /post_body {
        limit_except POST;
        client_max_body_size 100;
        autoindex off;
        upload_store uploads;
    }

    location /directory {
        return 301 /directory/;
    }

    location /directory/ {
        root eval_tests/YoupiBanane;
        index youpi.bad_extension;
        limit_except GET POST; # Aqui sim precisa do POST por causa do CGI
        autoindex off;
        cgi_pass .bla eval_tests/cgi_tester;
    }
}
