server {
    listen 8080;
    server_name localhost;

    # / GET only
    location / {
        limit_except GET {
            deny all;
        }
        root html;
    }

    # .bla files POST com cgi
    location ~ \.bla$ {
        limit_except POST {
            deny all;
        }
        cgi_pass ./cgi_test;
    }

    # /post_body POST com max body
    location /post_body {
        limit_except POST {
            deny all;
        }
        client_max_body_size 100;
    }

    # /directory/ com root em YoupiBanane
    location /directory/ {
        limit_except GET {
            deny all;
        }
        root YoupiBanane;
        index youpi.bad_extension;
    }
}