server {
    listen 8088;
    root www/;
    index index.html;

    location / {
        limit_except GET POST;
        autoindex off;
    }

    location /uploads {
        limit_except GET POST;
    }
}
