server {
    listen 0.0.0.0:8080;
    server_name localhost;
    client_max_body_size 200M;

    location / {
        root eval_tests/YoupiBanane;
        index youpi.bad_extension;
        limit_except GET;
        autoindex off;
        cgi_pass .bla eval_tests/cgi_tester;
    }

    location /directory {
        root eval_tests/YoupiBanane;
        index youpi.bad_extension;
        limit_except GET POST;
        autoindex off;
        cgi_pass .bla eval_tests/cgi_tester;
    }

    location /post_body {
        limit_except POST;
        client_max_body_size 100;
        autoindex off;
        upload_store uploads;
    }
}
