/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ConfigParser.cpp                                   :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jucoelho <jucoelho@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/07/17 11:46:22 by dajesus-          #+#    #+#             */
/*   Updated: 2026/07/30 18:49:18 by jucoelho         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

# include "config/ConfigParser.hpp"

# include <stdexcept>
# include <sstream>

/**
 * @brief Default constructor for ConfigParser.
 * Initializes an empty parser with no tokens and cursor at position 0.
 */
ConfigParser::ConfigParser(void) : _tokens(), _pos(0)
{
}

/**
 * @brief Parameterized constructor for ConfigParser.
 * @param tokens A vector of tokens generated by the Lexer to be parsed.
 */
ConfigParser::ConfigParser(const std::vector<Token> &tokens)
	: _tokens(tokens), _pos(0)
{
}

/**
 * @brief Copy constructor for ConfigParser.
 * @param copy The ConfigParser instance to copy.
 */
ConfigParser::ConfigParser(const ConfigParser &copy)
	: _tokens(copy._tokens), _pos(copy._pos)
{
}

/**
 * @brief Assignment operator for ConfigParser.
 * @param other The ConfigParser instance to assign from.
 * @return A reference to the updated ConfigParser instance.
 */
ConfigParser &ConfigParser::operator=(const ConfigParser &other)
{
	if (this != &other)
	{
		_tokens = other._tokens;
		_pos = other._pos;
	}
	return (*this);
}

/**
 * @brief Destructor for ConfigParser.
 */
ConfigParser::~ConfigParser(void)
{
}

/**
 * @brief Looks at the current token without consuming it.
 * @return A constant reference to the current Token.
 */
const Token &ConfigParser::peek(void) const
{
	return (_tokens[_pos]);
}

/**
 * @brief Consumes the current token and advances the parser's cursor.
 * @return A constant reference to the consumed Token.
 */
const Token &ConfigParser::advance(void)
{
	const Token &tok = _tokens[_pos];

	if (tok.type != TOKEN_EOF)
		_pos++;
	return (tok);
}

/**
 * @brief Checks if the current token matches a specific type.
 * @param type The token type to compare against.
 * @return true if the current token matches the specified type, false otherwise.
 */
bool ConfigParser::check(t_token_type type) const
{
	return (peek().type == type);
}

/**
 * @brief Enforces that the current token matches a specific type and consumes it.
 * If the token does not match, it halts parsing and throws a detailed error.
 * * @param type The expected token type.
 * @param expected A string description of what was expected (used for error messages).
 * @return A constant reference to the consumed Token.
 * @throw std::runtime_error if the current token type does not match the expected type.
 */
const Token &ConfigParser::expect(t_token_type type, const std::string &expected)
{
	if (!check(type))
	{
		std::ostringstream oss;

		oss << "Config error at line " << peek().line << ", column "
			<< peek().column << ": expected " << expected;
		throw std::runtime_error(oss.str());
	}
	return (advance());
}

/**
 * @brief Parses a single configuration entry, which can be either a Block or a Directive.
 * Reads the identifier and its arguments, then checks the terminating token:
 * - If it finds a '{', it parses a nested ConfigBlock.
 * - If it finds a ';', it parses a simple ConfigDirective.
 * * @param parent The parent ConfigBlock to which the parsed entry will be added.
 * @throw std::runtime_error if the syntax is invalid (missing '{', ';', or a valid name).
 */
void ConfigParser::parseEntry(ConfigBlock &parent)
{
	if (!check(TOKEN_WORD))
	{
		std::ostringstream oss;

		oss << "Config error at line " << peek().line << ", column "
			<< peek().column << ": expected directive or block name";
		throw std::runtime_error(oss.str());
	}

	Token					nameToken = advance();
	std::vector<std::string>	args;

	while (check(TOKEN_WORD))
		args.push_back(advance().value);

	if (check(TOKEN_LBRACE))
	{
		advance();

		ConfigBlock	block(nameToken.value, nameToken.line, nameToken.column);

		block.args = args;
		parseBlockBody(block);
		expect(TOKEN_RBRACE, "'}' to close block '" + nameToken.value + "'");
		parent.children.push_back(block);
		return ;
	}
	if (check(TOKEN_SEMICOLON))
	{
		advance();

		ConfigDirective	directive(nameToken.value, nameToken.line, nameToken.column);

		directive.args = args;
		parent.directives.push_back(directive);
		return ;
	}

	std::ostringstream oss;

	oss << "Config error at line " << peek().line << ", column "
		<< peek().column << ": expected '{' or ';' after '"
		<< nameToken.value << "'";
	throw std::runtime_error(oss.str());
}

/**
 * @brief Iteratively parses the interior contents of a configuration block.
 * Continues parsing entries until it encounters a closing right brace '}' or the end of the file.
 * * @param block The ConfigBlock currently being populated.
 */
void ConfigParser::parseBlockBody(ConfigBlock &block)
{
	while (!check(TOKEN_RBRACE) && !check(TOKEN_EOF))
		parseEntry(block);
}

/**
 * @brief The main entry point for the Parser. 
 * Converts the flat vector of Tokens into an Abstract Syntax Tree (AST).
 * * @return The root ConfigBlock containing the entire parsed configuration.
 * @throw std::runtime_error if the token stream is empty or syntax is invalid.
 */
ConfigBlock ConfigParser::parse(void)
{
	if (_tokens.empty())
		throw std::runtime_error("Config error: empty token stream");

	ConfigBlock	root("config", 0, 0);

	parseBlockBody(root);
	expect(TOKEN_EOF, "end of file");
	return (root);
}
