/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Connection.cpp                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jucoelho <jucoelho@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/05 12:21:14 by jucoelho          #+#    #+#             */
/*   Updated: 2026/07/11 19:37:25 by jucoelho         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "network/Connection.hpp"
#include <sys/socket.h>
#include <unistd.h>

/**
 * @brief Default constructor for the Connection class.
 *
 * Initializes an empty and invalid connection, setting the file descriptor 
 * to -1 and recording the current timestamp as the creation time.
 */
Connection::Connection(void) : _client_fd(-1), _time(time(NULL)), _parser()
{
}

/**
 * @brief Parameterized constructor for the Connection class.
 *
 * Associates the class instance with an active client file descriptor (socket)
 * and records the current timestamp as the connection's first activity.
 *
 * @param client_fd The file descriptor generated by accept().
 */
Connection::Connection(int client_fd) : _client_fd(client_fd), _time(time(NULL)), _parser()
{
}

/**
 * @brief Copy constructor with ownership transfer.
 *
 * Copies the attributes of the source instance and deactivates the socket 
 * of the copied object to prevent two objects from managing or closing the same descriptor.
 *
 * @note The use of const_cast is a strategy in C++98 to emulate move semantics, 
 * ensuring that only one instance of Connection owns and closes the file descriptor.
 *
 * @param copy Constant reference to the source object.
 */
Connection::Connection(const Connection &copy)
	: _client_fd(copy._client_fd),
	  _write_buffer(copy._write_buffer),
	  _time(copy._time),
	  _parser(copy._parser)
{
	const_cast<Connection&>(copy)._client_fd = -1;
}

/**
 * @brief Copy assignment operator with ownership transfer.
 *
 * If instances are different, closes the current descriptor (if valid), takes 
 * ownership of the new descriptor by invalidating the source via const_cast, 
 * and copies the buffer, parser, and time states.
 *
 * @param other Constant reference to the object to be assigned.
 * @return Reference to the current instance (*this).
 */
Connection &Connection::operator=(const Connection &other)
{
	if (this != &other)
	{
		if (_client_fd >= 0)
			close(_client_fd);
		_client_fd = other._client_fd;
		const_cast<Connection&>(other)._client_fd = -1;
		_write_buffer = other._write_buffer;
		_time = other._time;
		_parser = other._parser;
	}
	return (*this);
}

/**
 * @brief Destructor for the Connection class.
 *
 * Ensures the safe closure of the client's file descriptor (RAII) if it still 
 * holds ownership of a valid socket (greater than or equal to 0).
 */
Connection::~Connection(void)
{
	if (_client_fd >= 0)
		close(_client_fd);
}

/**
 * @brief Reads pending data from the client socket and feeds it to the HTTP parser.
 *
 * Allocates a temporary local buffer to read raw bytes from the network using recv(). 
 * If new bytes are received, it feeds the parser's state machine and updates 
 * the last activity timestamp of the connection.
 *
 * @return The number of bytes successfully read, 0 if the client disconnected, 
 * or -1 in case of an error/lack of data (EAGAIN/EWOULDBLOCK).
 */
ssize_t Connection::receive_data(void)
{
	char	buffer[4096];
	ssize_t	bytes_read;

	bytes_read = recv(_client_fd, buffer, sizeof(buffer), 0);
	if (bytes_read > 0)
	{
		_parser.feed(buffer, bytes_read);
		_time = time(NULL);
	}
	return (bytes_read);
}

/**
 * @brief Sends accumulated data from the write buffer back to the client.
 *
 * Attempts to transmit the contents of _write_buffer using the send() system call. 
 * If it manages to send part or all of the data, it removes the transmitted bytes 
 * from the buffer and updates the activity timestamp.
 *
 * @return The number of bytes successfully sent, or -1 in case of an I/O error.
 */
ssize_t Connection::send_data(void)
{
	ssize_t	sent = send(_client_fd, _write_buffer.data(),
						_write_buffer.size(), 0);
	if (sent > 0)
	{
		_write_buffer.erase(0, sent);
		_time = time(NULL);
	}
	return (sent);
}

/**
 * @brief Checks if the connection has pending data to be sent.
 *
 * @return true if the write buffer is not empty, false otherwise.
 */
bool	Connection::has_data_to_send(void) const
{
	return (!_write_buffer.empty());
}

/**
 * @brief Sets or updates the contents of the write buffer.
 *
 * @param data String containing the raw HTTP response data to be stored.
 */
void	Connection::set_write_buffer(const std::string &data)
{
	_write_buffer = data;
}

/**
 * @brief Completely clears the content of the write buffer.
 *
 * Used after finishing transmissions or when resetting the transmission cycle.
 */
void	Connection::reset_write_buffer(void)
{
	_write_buffer.clear();
}

/**
 * @brief Calculates the time elapsed since the last activity on this connection.
 *
 * This comparison is used by the server to monitor timeouts of inactive connections.
 *
 * @return The number of seconds (as a double) since the last successful 
 * read or write call.
 */
double Connection::last_activity(void) const
{
	return (difftime(time(NULL), _time));
}

/**
 * @brief Retrieves the current state of the HTTP parser associated with this connection.
 *
 * @return The t_psr_state enum/type indicating which stage of the request the parser is in.
 */
t_psr_state Connection::get_psr_state(void) const
{
	return _parser.get_psr_state();
}

/**
 * @brief Returns a constant reference to the processed HTTP request object.
 *
 * Allows external modules to query the already parsed information (method, URL, headers) 
 * without modifying the original structure of the parser.
 *
 * @return Constant reference to the HttpRequest instance.
 */
const HttpRequest& Connection::getRequest(void) const
{
	return _parser.getRequest();
}